title: Meet Shah's Technical Blog
description: Insights on AI, Cloud Management, and DevSecOps
baseurl: ""
url: "https://shahmeetk.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
