name: Direct Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Deploy
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          gh-pages -d . -b gh-pages -t true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
